# Generated by Django 3.0.7 on 2021-01-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=250)),
                ('brand', models.CharField(max_length=250)),
                ('categories', models.CharField(choices=[('Guitar', 'Guitar'), ('Bass', 'Bass')], max_length=250)),
                ('color', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
                ('description', models.TextField(max_length=1000)),
                ('product_photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('product_photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('product_photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('product_photo_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
            ],
        ),
    ]
