# Generated by Django 3.0.7 on 2021-01-16 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_shop_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='created_date',
        ),
    ]
