# Generated by Django 3.0.7 on 2021-01-16 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_shop_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
